-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 19:05:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `isAdmin` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta` (
  `idPregunta` INT NOT NULL,
  `pregunta` VARCHAR(100) NOT NULL,
  `respuestaFalsaUno` VARCHAR(100) NOT NULL,
  `respuestaFalsa2` VARCHAR(45) NULL,
  `respuestaFalsa3` VARCHAR(45) NULL,
  `RespustaCorrecta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emision` (
  `idEmision` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`idEmision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta_has_Emision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta_has_Emision` (
  `Pregunta_idPregunta` INT NOT NULL,
  `Emision_idEmision` INT NOT NULL,
  PRIMARY KEY (`Pregunta_idPregunta`, `Emision_idEmision`),
  INDEX `fk_Pregunta_has_Emision_Emision1_idx` (`Emision_idEmision` ASC),
  INDEX `fk_Pregunta_has_Emision_Pregunta1_idx` (`Pregunta_idPregunta` ASC),
  CONSTRAINT `fk_Pregunta_has_Emision_Pregunta1`
    FOREIGN KEY (`Pregunta_idPregunta`)
    REFERENCES `mydb`.`Pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_has_Emision_Emision1`
    FOREIGN KEY (`Emision_idEmision`)
    REFERENCES `mydb`.`Emision` (`idEmision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participante` (
  `Usuario_idUsuario` INT NOT NULL,
  `Emision_idEmision` INT NOT NULL,
  `isWinner` INT NOT NULL DEFAULT 1,
  `puntaje` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Usuario_idUsuario`, `Emision_idEmision`),
  INDEX `fk_Usuario_has_Emision_Emision1_idx` (`Emision_idEmision` ASC),
  INDEX `fk_Usuario_has_Emision_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Emision_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Emision_Emision1`
    FOREIGN KEY (`Emision_idEmision`)
    REFERENCES `mydb`.`Emision` (`idEmision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
